name: deploy
on:
    push:
        branches: ['main']

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: SSH Commands
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ vars.SSH_HOST }}
                  port: ${{ vars.SSH_PORT }}
                  username: ${{ vars.SSH_USER }}
                  key: ${{ vars.SSH_PRIVATE_KEY }}
                  script: |
                      umask 022
                      cd internal-warehouse-frontend
                      git reset --hard
                      git pull origin main
                      npm install --legacy-peer-deps
                      npm run-script ng build
